### ISSUE TITLE
Install instructions not working

### ISSUE THREAD

**Issue by bigardone** [antew/vim-elm-language-server#1]
Hi @antew! I'm trying to install this plugin to use it from Coc, but when I run `npm i -g elm-language-server` it doesn't seem to find the package:

```
$ npm i -g elm-language-server

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/elm-language-server - Not found
npm ERR! 404
npm ERR! 404  'elm-language-server@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Is there anything I'm missing? Thanks in advance :)

**Comment by razzeee** [comment]
I think this has been solved?

**Comment by hpate-omicron** [comment]
I think we'd need elm-language-server to be published as an npm package so that it would be available at https://www.npmjs.com/package/elm-language-server

With the vscode extension it is being bundled in as a git submodule with the extension correct?

The current way I've been installing it is
```
$ git clone https://github.com/elm-tooling/elm-language-server.git
$ cd elm-language-server
$ npm install
$ npm link
```

**Comment by razzeee** [comment]
Yes, figured that, I first want to move the tree sitter implementation to wasm and then create a npm release.

**Comment by antew** [comment]
Sounds good, I updated the readme for the current install steps, should work well in the meantime :)
